/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package os;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Moshiur Rahman
 */
public class power extends javax.swing.JFrame {

    /**
     * Creates new form power
     */
    public power() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shutdown = new javax.swing.JLabel();
        restart = new javax.swing.JLabel();
        sleep = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        shutdown.setText("  Shut Down");
        shutdown.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        shutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shutdownMouseClicked(evt);
            }
        });
        getContentPane().add(shutdown);
        shutdown.setBounds(0, 0, 400, 30);

        restart.setText("  Restart");
        restart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        restart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restartMouseClicked(evt);
            }
        });
        getContentPane().add(restart);
        restart.setBounds(0, 30, 400, 30);

        sleep.setText("  Sleep");
        sleep.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sleep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sleepMouseClicked(evt);
            }
        });
        getContentPane().add(sleep);
        sleep.setBounds(0, 60, 400, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartMouseClicked
         try {
            // TODO add your handling code here:
            Runtime runtime = Runtime.getRuntime();
            Process proc = runtime.exec("shutdown -r\"");//restart
            System.exit(0);
        } catch (IOException ex) {
           // Logger.getLogger(DesTop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_restartMouseClicked

    private void shutdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shutdownMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Runtime runtime = Runtime.getRuntime();
            Process proc = runtime.exec("shutdown -s -t 0");
            System.exit(0);
        } catch (IOException ex) {
           // Logger.getLogger(DesTop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_shutdownMouseClicked

    private void sleepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sleepMouseClicked
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Runtime runtime = Runtime.getRuntime();
            Process proc = runtime.exec("cmd /c shutdown -l");//sleep
            System.exit(0);
        } catch (IOException ex) {
           // Logger.getLogger(DesTop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sleepMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(power.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(power.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(power.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(power.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new power().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel restart;
    private javax.swing.JLabel shutdown;
    private javax.swing.JLabel sleep;
    // End of variables declaration//GEN-END:variables
}
